name: finplan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  ms_undraw: ^3.0.1+1
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter_snake_navigationbar: ^0.6.0
  pie_chart: ^5.1.0
  easy_localization: ^3.0.0
  qr_code_scanner: ^0.6.1
  connectivity_plus: ^2.2.0
  upgrader: ^3.12.1
  table_calendar: ^3.0.3
  awesome_notifications: ^0.0.6+12 #leave at 0.0.6+12 update after 0.7.0 comes out, error on 0.6.0
  firebase_messaging: ^11.2.6
  intro_slider: ^3.0.3
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
